devel/shiboken2: limit supported python versions
With python 3.10:

pyside-setup-opensource-src-5.15.2/sources/shiboken2/libshiboken/pep384impl.cpp:755:12: error: use of undeclared identifier '_Py_Mangle'
    return _Py_Mangle(privateobj, name);
           ^
pyside-setup-opensource-src-5.15.2/sources/shiboken2/libshiboken/sbkstring.cpp:250:23: error: expression is not assignable
        Py_REFCNT(ob) = 1;
        ~~~~~~~~~~~~~ ^

Also mark BROKEN with python < 3.8 due to plist issues

Approved by:	portmgr blanket