www/firefox-esr: Unbreak build with Rust 1.56.0
error[E0557]: feature has been removed
   --> /wrkdirs/usr/ports/www/firefox-esr/work/firefox-78.15.0/third_party/rust/packed_simd/src/lib.rs:202:41
    |
202 | #![cfg_attr(use_const_generics, feature(const_generics))]
    |                                         ^^^^^^^^^^^^^^ feature has been removed
    |
    = note: removed in favor of `#![feature(adt_const_params]` and `#![feature(generic_const_exprs)]`

http://package18.nyi.freebsd.org/data/122amd64-default-foo/2021-10-19_17h56m28s/logs/errors/firefox-esr-78.15.0_2,1.log

PR:		259251