devel/py-Products.PloneLanguageTool: Fix build with setuptools 58.0.0+
- Bump PORTREVISION for package change

The isTranslatable method is deprecated and it causes SyntaxError.

byte-compiling /wrkdirs/usr/ports/devel/py-Products.PloneLanguageTool/work-py38/stage/usr/local/lib/python3.8/site-packages/Products/PloneLanguageTool/skins/LanguageTool/isTranslatable.py to isTranslatable.cpython-38.pyc
writing byte-compilation script '/tmp/tmpiy55_zr9.py'
/usr/local/bin/python3.8 /tmp/tmpiy55_zr9.py
  File "/usr/local/lib/python3.8/site-packages/Products/PloneLanguageTool/skins/LanguageTool/isTranslatable.py", line 11
SyntaxError: 'return' outside function

With hat:	python