www/firefox: Unbreak build with Rust 1.56.0
error[E0557]: feature has been removed
   --> /wrkdirs/usr/ports/www/firefox/work/firefox-93.0/third_party/rust/packed_simd/src/lib.rs:203:5
    |
203 |     const_generics,
    |     ^^^^^^^^^^^^^^ feature has been removed
    |
    = note: removed in favor of `#![feature(adt_const_params]` and `#![feature(generic_const_exprs)]`

http://package18.nyi.freebsd.org/data/122amd64-default-foo/2021-10-19_17h56m28s/logs/errors/firefox-93.0_2,2.log

PR:		259251