editors/vscode: update to 1.62.3
While here, temporarily mark as BROKEN on FreeBSD 12. One of the
native node modules does not compile with the following error:

In file included from ../src/keyboard_x.cc:6:
../src/keymapping.h:40:3: error: unknown type name 'pthread_t'; did you mean 'pthread'?
  pthread_t tid;
  ^~~~~~~~~
  pthread
/usr/include/stdio.h:157:9: note: 'pthread' declared here
        struct pthread *_fl_owner;      /* current owner */
               ^
In file included from ../src/keyboard_x.cc:6:
../src/keymapping.h:40:13: error: field has incomplete type 'pthread'
  pthread_t tid;
            ^
/usr/include/stdio.h:157:9: note: forward declaration of 'pthread'
        struct pthread *_fl_owner;      /* current owner */
               ^
2 errors generated.

A fix to the node module has been proposed at:
https://github.com/microsoft/node-native-keymap/pull/31

Changelog:
- https://code.visualstudio.com/updates/v1_59
- https://code.visualstudio.com/updates/v1_60
- https://code.visualstudio.com/updates/v1_61
- https://code.visualstudio.com/updates/v1_62