devel/py-jupyterlab-widgets: update supported python versions
RuntimeError: ensure_python is deprecated and not compatible with Python 3.10+
Skipping npm install as requested.

Approved by:	portmgr blanket