emulators/open-vm-tools: fix build after 2587b74c6187 removed NDF_ONLY_PNBUF
After base commit 2587b74c6187, which removed NDF_ONLY_PNBUF,
emulators/open-vm-tools fails to build, with:

--- vfsops.o ---
vfsops.c:190:16: error: use of undeclared identifier 'NDF_ONLY_PNBUF'; did you mean 'NDFREE_PNBUF'?
   NDFREE(ndp, NDF_ONLY_PNBUF);
               ^~~~~~~~~~~~~~
               NDFREE_PNBUF
/usr/src/sys/sys/namei.h:291:6: note: 'NDFREE_PNBUF' declared here
void NDFREE_PNBUF(struct nameidata *);
     ^

Indeed, NDFREE_PNBUF() should now be used.

PR:		263041
Approved by:	garga (maintainer)
MFH:		2022Q2