devel/libpeas: work around incomplete target dependency
../tests/libpeas/extension-c.c:32:10: fatal error: 'plugins/embedded/embedded-resources.h' file not found
 #include "plugins/embedded/embedded-resources.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

PR:		259080
Reported by:	antoine (via exp-run)
Regressed by:	https://github.com/mesonbuild/meson/commit/22c38a000673