devel/concurrencpp: fix build on powerpc64le on 13.0-RELEASE
When building with LLVM11 (and 12):
fatal error: error in backend: failed to perform tail call elimination on a call site marked musttail

LLVM13 doesn't have this issue.