textproc/fcitx5-qt: Update to 5.0.8
Fix the following error when building on CURRENT as well:

	/wrkdirs/usr/ports/textproc/fcitx5-qt/work/fcitx5-qt-5.0.7/qt5/platforminputcontext/qfcitxplatforminputcontext.cpp:973:31: error: implicit instantiation of undefined template 'std::array<char, 256>'
	        std::array<char, 256> buffer;

Sponsored by:	The FreeBSD Foundation
Approved by:	ygy