multimedia/libmediaart: unbreak build with Meson 0.62.0
ERROR: Error in gtkdoc helper script:
ld: error: unable to find library -lmediaart-2.0

PR:		262465
Reported by:	antoine (via exp-run)
Regressed by:	https://github.com/mesonbuild/meson/commit/457fb53ea46