devel/cargo-c: unbreak with libressl after 5c5878b7d124
error: failed to run custom build command for `openssl-sys v0.9.67`

Caused by:
  process didn't exit successfully: `../target/release/build/openssl-sys-27209cbe1c4dcecb/build-script-main` (exit status: 101)

  --- stderr
  thread 'main' panicked at '

  This crate is only compatible with OpenSSL 1.0.1 through 1.1.1, or LibreSSL 2.5
  through 3.4.0, but a different version of OpenSSL was found. The build is now aborting
  due to this version mismatch.

  ', cargo-crates/openssl-sys-0.9.67/build/main.rs:279:5
  stack backtrace:
     0: std::panicking::begin_panic
     1: build_script_main::version_error
     2: build_script_main::validate_headers
     3: build_script_main::main
     4: core::ops::function::FnOnce::call_oncex

PR:		260269
Submitted by:	lysfjord.daniel@smokepit.net (based on)
Obtained from:	upstream