www/rubygem-rack-timeout: update to 0.6.3
Required for gitlab-ce 15.1
Changelog:
https://github.com/zombocom/rack-timeout/blob/v0.6.3/CHANGELOG.md

0.6.3

    Fix NoMethodError: undefined method 'logger' for Rails:Module when Rails is defined as a Module, but is not a full Rails app (#180)

0.6.2

    Migrate CI from Travis CI to GitHub Actions (#182)
    Rails 7+ support (#184)

0.6.1

    RACK_TIMEOUT_TERM_ON_TIMEOUT can be set to zero to disable (#161)
    Update the gemspec's homepage to the current repo URL(#183)

0.6.0

    Allow sending SIGTERM to workers on timeout (#157)