graphics/mesa-dri: Fix PLIST
- Bump PORTREVISION for package change

===> Checking for pkg-plist issues (check-plist)
===> Parsing plist
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: share/drirc.d/00-radv-defaults.conf
===> Checking for items in pkg-plist which are not in STAGEDIR
===> Error: Plist issues found.
*** Error code 1

Stop.
make: stopped in /usr/ports/graphics/mesa-dri
=>> Error: check-plist failures detected

Approved by:	portmgr (blanket)