comms/hamlib:  Update to 4.4
- Some patches not needed now due to adrian@ patches sent upstream.

- Additional changes by @takefu

The distribution tarball uses patch applied to the following master branch because the build is broken.

https://github.com/Hamlib/Hamlib/commit/baea7e8c9a30ddf051cd04deec1b715856e4ed83#diff-9df9e2c313e694cf242534e90c1187fe119fac8de7c304ae438de0736209953b.patch

The error message in build is as follows.
hamlibpy_wrap.c:48824:80: error: use of undeclared identifier 'RIG_FUNCTION_SEND_VOICE_MEM'; did you mean 'RIG_FUNCTION_SEND_MORSE'?
  SWIG_Python_SetConstant(d, "RIG_FUNCTION_SEND_VOICE_MEM",SWIG_From_int((int)(RIG_FUNCTION_SEND_VOICE_MEM)));

For a complete log of changes to Hamlib, please visit:

http://sourceforge.net/p/hamlib/code/commit_browser

Major changes in 4.0 affecting usage
Most rig model numbers have changed
RIG_LEVEL_VOX has been deprecated and replaced by RIG_LEVEL_VOXDELAY
rigctl 'f' command now returns VFO argument too
rigctl 'y' and 'Y' command now take/show antenna argument and option.
range_list items are undergoing changes towards a different model TBD
RTS/DTR PTT sharing is off by default now -- use serial_share=1 option to
enable

PR:		ports/261105
Reported by:	takefu@airport.gm