lang/rust-nightly: Update to 1.60.0.20220204
Turn off DOCS:

error[E0432]: unresolved import `crate::sys::cvt`
  --> library/std/src/os/fd/owned.rs:12:5
   |
12 | use crate::sys::cvt;
   |     ^^^^^^^^^^^^^^^ no `cvt` in `sys`

error: Compilation failed, aborting rustdoc

For more information about this error, try `rustc --explain E0432`.
error: could not document `std`

http://beefy18.nyi.freebsd.org/data/main-amd64-default/p85f832623ad8_se2fe58d61b/logs/rust-nightly-1.60.0.20220202.log

https://github.com/rust-lang/rust/compare/2681f253bcdb31a274411d2be456e7c6a1c67d62...71226d717a1fb57122e47e63b97295e703319cb0