devel/libsoup3: Fix PLIST
- Bump PORTREVISION for package change

====> Checking for pkg-plist issues (check-plist)
===> Parsing plist
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: share/locale/ab/LC_MESSAGES/libsoup-3.0.mo
===> Checking for items in pkg-plist which are not in STAGEDIR
===> Error: Plist issues found.
*** Error code 1

Stop.
make: stopped in /usr/ports/devel/libsoup3

Approved by:	portmgr (blanket)