sysutils/dtc: fix clang 14 warning about use of bitwise logical operator
During an exp-run for llvm 14 (see bug 261742), it turned out that
sysutils/dtc fails to build with clang 14:

libfdt/fdt_rw.c:438:6: error: use of bitwise '|' with boolean operands [-Werror,-Wbitwise-instead-of-logical]
        if (can_assume(LIBFDT_ORDER) |
            ^~~~~~~~~~~~~~~~~~~~~~~~~~
                                     ||
libfdt/libfdt_internal.h:171:29: note: expanded from macro 'can_assume'
                                ^
libfdt/fdt_rw.c:438:6: note: cast one or both operands to int to silence this warning
libfdt/libfdt_internal.h:171:29: note: expanded from macro 'can_assume'
                                ^

This should have been a logical or instead. Upstream fixed this in:
https://github.com/dgibson/dtc/commit/7be250b4d059771c47be00ec8d4df7f47e4ac77c

PR:		261930
Approved by:	maintainer timeout (2 weeks)
MFH:		2022Q1