archivers/ccmix: unbreak the build against unsigned-by-default char
On ARM, PowerPC, RISC-V (of the architectures supported by FreeBSD)
char type is unsigned by default, which causes the following build
error due to incorrect array declaration:

  mixkey/mix_dexoder.cpp:17:5: error: constant expression evaluates
  to -1 which cannot be narrowed to type 'char' [-Wc++11-narrowing]