net-p2p/gtk-gnutella: fix packaging on powerpc*
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: %%DATADIR%%/powerpc-%%OPSYS%%/gtk-gnutella.nm
===> Checking for items in pkg-plist which are not in STAGEDIR
Error: Missing: %%DATADIR%%/%%ARCH%%-%%OPSYS%%/gtk-gnutella.nm
===> Error: Plist issues found.