devel/py-apscheduler: drop all pytest workarounds after 2ada39de05b1
______________________________________________ TestProcessJobs.test_nonexistent_executor _______________________________________________

self = <tests.test_schedulers.TestProcessJobs object at 0x878ac2880>
scheduler = <tests.test_schedulers.DummyScheduler object at 0x895538460>, jobstore = <MagicMock spec='BaseJobStore' id='36865062272'>
caplog = <_pytest.logging.LogCaptureFixture object at 0x89480f130>

    def test_nonexistent_executor(self, scheduler, jobstore, caplog):
        """
        Test that an error is logged and the job is removed from its job store if its executor is
        not found.

        """
>       caplog.setLevel(logging.ERROR)
E       AttributeError: 'LogCaptureFixture' object has no attribute 'setLevel'

tests/test_schedulers.py:813: AttributeError
______________________________________________ TestProcessJobs.test_max_instances_reached ______________________________________________

self = <tests.test_schedulers.TestProcessJobs object at 0x878ac2a30>
scheduler = <tests.test_schedulers.DummyScheduler object at 0x893c45460>, job = <MagicMock spec='Job' id='36851155008'>
jobstore = <MagicMock spec='BaseJobStore' id='36838894800'>, executor = <MagicMock spec='BaseExecutor' id='36851346448'>
caplog = <_pytest.logging.LogCaptureFixture object at 0x893c4b940>

    def test_max_instances_reached(self, scheduler, job, jobstore, executor, caplog):
        """Tests that a warning is logged when the maximum instances of a job is reached."""
>       caplog.setLevel(logging.WARNING)
E       AttributeError: 'LogCaptureFixture' object has no attribute 'setLevel'

tests/test_schedulers.py:824: AttributeError
_________________________________________________ TestProcessJobs.test_executor_error __________________________________________________

self = <tests.test_schedulers.TestProcessJobs object at 0x878ac2c10>
scheduler = <tests.test_schedulers.DummyScheduler object at 0x89482ea00>, jobstore = <MagicMock spec='BaseJobStore' id='36865031376'>
executor = <MagicMock spec='BaseExecutor' id='36865028928'>, caplog = <_pytest.logging.LogCaptureFixture object at 0x895534ac0>

    def test_executor_error(self, scheduler, jobstore, executor, caplog):
        """Tests that if any exception is raised in executor.submit(), it is logged."""
>       caplog.setLevel(logging.ERROR)
E       AttributeError: 'LogCaptureFixture' object has no attribute 'setLevel'

tests/test_schedulers.py:834: AttributeError